name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run build
      run: npm run build

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Initialize Supabase
      run: |
        supabase init --force
        supabase db start
        supabase db reset
        
        echo "Debug: Supabase Status Output"
        supabase status
        echo "--------------------"
        
        # Get Supabase credentials with debug output
        echo "Extracting API URL..."
        supabase status | grep 'API URL'
        API_URL=$(supabase status | grep 'API URL' | cut -d':' -f2- | xargs)
        echo "API_URL=$API_URL"
        
        echo "Extracting service role key..."
        supabase status | grep 'service_role key'
        SERVICE_ROLE_KEY=$(supabase status | grep 'service_role key' | cut -d':' -f2- | xargs)
        echo "SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY"
        
        echo "Extracting anon key..."
        supabase status | grep 'anon key'
        ANON_KEY=$(supabase status | grep 'anon key' | cut -d':' -f2- | xargs)
        echo "ANON_KEY=$ANON_KEY"
        
        # Export for other steps
        echo "SUPABASE_URL=$API_URL" >> $GITHUB_ENV
        echo "SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY" >> $GITHUB_ENV
        echo "SUPABASE_ANON_KEY=$ANON_KEY" >> $GITHUB_ENV
        
        # Create cypress.env.json
        echo "{
          \"SUPABASE_URL\": \"$API_URL\",
          \"SUPABASE_ANON_KEY\": \"$ANON_KEY\",
          \"SUPABASE_SERVICE_ROLE_KEY\": \"$SERVICE_ROLE_KEY\"
        }" > cypress.env.json
        
        echo "Supabase initialized with URL: $API_URL"
        echo "Created cypress.env.json with credentials"
        cat cypress.env.json
    
    - name: Seed Database
      run: npm run seed-users:ci
    
    - name: Run E2E tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        command: npm run test:e2e