name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run build
      run: npm run build

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Initialize Supabase
      run: |
        supabase init --force
        npm run supabase:start
        npm run supabase:env
        # Create cypress.env.json from .env
        node -e "
          const fs = require('fs');
          const dotenv = require('dotenv');
          const env = dotenv.parse(fs.readFileSync('.env'));
          const cypressEnv = {
            SUPABASE_URL: env.API_URL,
            SUPABASE_ANON_KEY: env.ANON_KEY,
            SUPABASE_SERVICE_ROLE_KEY: env.SERVICE_ROLE_KEY
          };
          fs.writeFileSync('cypress.env.json', JSON.stringify(cypressEnv, null, 2));
        "
        echo "Created cypress.env.json with credentials:"
        cat cypress.env.json
    
    - name: Seed Database
      run: npm run seed-users:ci
    
    - name: Run E2E tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        command: npm run test:e2e